;;; siren-coffee.el --- jimeh's Emacs Siren: coffee-mode configuration.

;;; Commentary:

;; Basic configuration for coffee-mode.

;;; Code:

(use-package coffee-mode
  :mode "\\.coffee\\'"
  :interpreter "coffee"

  :config
  (require 'siren-programming)

  (setq coffee-tab-width 2)

  (defun siren-coffee-mode-defaults ()
    (siren-prog-mode-defaults)

    ;; remove the "Generated by CoffeeScript" header
    (add-to-list 'coffee-args-compile "--no-header")

    ;; Update the already compiled js on save
    (and (buffer-file-name)
         (file-exists-p (buffer-file-name))
         (file-exists-p (coffee-compiled-file-name (buffer-file-name)))
         (coffee-cos-mode t))

    (setq tab-width 2)
    (highlight-indentation-current-column-mode)
    (subword-mode +1))

  (setq siren-coffee-mode-hook 'siren-coffee-mode-defaults)
  (add-hook 'coffee-mode-hook (lambda ()
                                (run-hooks 'siren-coffee-mode-hook))))

(provide 'siren-coffee)
;;; siren-coffee.el ends here
