;;; siren-coffee.el --- jimeh's Emacs Siren: coffee-mode configuration.

;;; Commentary:

;; Basic configuration for coffee-mode.

;;; Code:

(require 'siren-programming)

(use-package coffee-mode
  :mode "\\.coffee\\'"
  :interpreter "coffee"
  :hook (coffee-mode . siren-coffee-mode-setup)

  :init
  (defun siren-coffee-mode-setup ()
    (siren-prog-mode-setup)

    ;; remove the "Generated by CoffeeScript" header
    (add-to-list 'coffee-args-compile "--no-header")

    ;; Update the already compiled js on save
    (and (buffer-file-name)
         (file-exists-p (buffer-file-name))
         (file-exists-p (coffee-compiled-file-name (buffer-file-name)))
         (coffee-cos-mode t))

    (setq tab-width 2)
    (highlight-indentation-current-column-mode)
    (subword-mode +1))

  :config
  (setq coffee-tab-width 2))

(provide 'siren-coffee)
;;; siren-coffee.el ends here
