(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-menu-height 15)
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 211 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(autopair-global-mode t)
 '(backup-directory-alist (quote (("." . "~/.saves"))))
 '(column-number-mode t)
 '(display-time-24hr-format t)
 '(display-time-day-and-date nil)
 '(display-time-interval 10)
 '(display-time-load-average-threshold 1.0)
 '(display-time-mode t)
 '(egg-enable-tooltip t)
 '(egg-git-command "git")
 '(egg-mode-key-prefix "C-x g")
 '(egg-patch-command "/usr/bin/patch")
 '(egg-refresh-index-in-backround t)
 '(elscreen-display-tab t)
 '(elscreen-tab-display-control t)
 '(elscreen-tab-display-kill-screen nil)
 '(fci-rule-color "#593B38")
 '(fci-rule-width 1)
 '(fill-column 80)
 '(global-auto-revert-mode t)
 '(global-undo-tree-mode t)
 '(history-length 500)
 '(icomplete-mode t)
 '(ispell-program-name "aspell")
 '(markdown-command "redcarpet")
 '(ns-tool-bar-display-mode nil t)
 '(ns-tool-bar-size-mode nil t)
 '(php-mode-dot-property-warning t)
 '(ruby-deep-indent-paren nil)
 '(safe-local-variable-values (quote ((eval rainbow-mode 1))))
 '(show-paren-mode t)
 '(speedbar-show-unknown-files t)
 '(standard-indent 2)
 '(tabbar-mode nil)
 '(textmate-mode t)
 '(tool-bar-mode nil)
 '(undo-tree-mode-lighter "")
 '(visual-line-mode nil t)
 '(whitespace-action nil)
 '(winner-mode t nil (winner))
 '(yas/global-mode t nil (yasnippet))
 '(yas/snippet-dirs (quote ("~/.emacs.d/snippets/custom" "~/.emacs.d/snippets/stock" "~/.emacs.d/el-get/yasnippet/snippets")) nil (yasnippet))
 '(yas/use-menu t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
