(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-auto-show-menu 0.2)
 '(ac-delay 0.05)
 '(ac-menu-height 15)
 '(ack-arguments (quote ("--ignore-dir=vendor/ruby" "--ignore-dir=vendor/bundle" "--ignore-dir=coverage" "--ignore-dir=docs" "--ignore-dir=doc" "--type-add=js=.js,.js.erb" "--type-add=ruby=.jbuilder,.rabl" "--type-add=html=.haml,.hamlc,.jade" "--type-add=css=.sass,.scss,.styl" "--type-set=coffee=.coffee" "--type-set=cucumber=.feature")))
 '(ack-project-root-file-patterns (quote (".project\\'" ".xcodeproj\\'" ".sln\\'" "\\`Project.ede\\'" "\\`.git\\'" "\\`.bzr\\'" "\\`_darcs\\'" "\\`.hg\\'" "\\`Gemfile\\'" "\\`Rakefile\\'" "\\`Makefile\\'")))
 '(ack-prompt-for-directory (quote unless-guessed))
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 211 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(autopair-global-mode t)
 '(column-number-mode t)
 '(display-time-24hr-format t)
 '(display-time-day-and-date nil)
 '(display-time-interval 10)
 '(display-time-load-average-threshold 1.0)
 '(display-time-mode t)
 '(ecb-basic-buffer-sync (quote (Info-mode dired-mode magit-mode)))
 '(ecb-create-layout-file "~/.emacs.d/ecb-user-layouts.el")
 '(ecb-layout-name "left13")
 '(ecb-options-version "2.40")
 '(ecb-primary-secondary-mouse-buttons (quote mouse-1--mouse-2))
 '(ecb-source-path (quote (("~/Projects" "Projects") ("~/.emacs.d" ".emacs.d") ("~/.dotfiles" ".dotfiles") ("~/Projects/fitzdares" "fitzdares") ("~/src" "src") ("~/Sites" "Sites") ("~" "~") ("/" "/"))))
 '(ecb-tip-of-the-day nil)
 '(ecb-toggle-layout-sequence (quote ("left13" "left15")))
 '(ecb-tree-indent 3)
 '(ecb-tree-make-parent-node-sticky nil)
 '(ecb-windows-width 0.22)
 '(elscreen-display-tab t)
 '(elscreen-tab-display-control t)
 '(elscreen-tab-display-kill-screen nil)
 '(eproject-completing-read-function (quote eproject--ido-completing-read))
 '(evil-default-cursor (quote (t)))
 '(fci-handle-truncate-lines nil)
 '(fci-rule-width 1)
 '(fill-column 78)
 '(fringe-mode 0 nil (fringe))
 '(global-auto-revert-mode t)
 '(global-undo-tree-mode t)
 '(history-length 500)
 '(icomplete-mode t)
 '(ispell-program-name "aspell")
 '(magit-completing-read-function (quote magit-ido-completing-read))
 '(magit-default-tracking-name-function (quote magit-default-tracking-name-branch-only))
 '(magit-repo-dirs (quote ("~/Projects" "~/.dotfiles" "~/.emacs.d")))
 '(magit-status-buffer-switch-function (quote switch-to-buffer))
 '(markdown-command "redcarpet")
 '(minimap-width-fraction 0.1)
 '(minimap-window-location (quote right))
 '(ns-tool-bar-display-mode nil t)
 '(ns-tool-bar-size-mode nil t)
 '(nxhtml-skip-welcome t)
 '(org-agenda-files (list "~/.org-files/todos.org" "~/.org-files/notes.org" "~/.org-files/events.org"))
 '(org-agenda-ndays 7)
 '(org-agenda-show-all-dates t)
 '(org-agenda-skip-deadline-if-done t)
 '(org-agenda-skip-scheduled-if-done t)
 '(org-agenda-start-on-weekday nil)
 '(org-deadline-warning-days 14)
 '(org-default-notes-files "~/.org-files/notes.org")
 '(org-directory "~/.org-files/")
 '(org-fast-tag-selection-single-key (quote expert))
 '(org-log-done t)
 '(org-remember-store-without-prompt t)
 '(org-remember-templates (quote (("Todo" 116 "** TODO %?
" "~/.org-files/todos.org" "Tasks") ("Note" 110 "** %?
" "~/.org-files/notes.org" "Notes"))))
 '(org-reverse-note-order t)
 '(php-mode-dot-property-warning t)
 '(ruby-deep-indent-paren nil)
 '(ruby-use-encoding-map nil)
 '(safe-local-variable-values (quote ((eval rainbow-mode 1))))
 '(scss-compile-at-save nil)
 '(smooth-scroll-margin 6)
 '(speedbar-show-unknown-files t)
 '(standard-indent 2)
 '(tabbar-mode nil)
 '(tool-bar-mode nil)
 '(undo-limit 160000)
 '(undo-strong-limit 240000)
 '(undo-tree-mode-lighter "")
 '(visual-line-mode nil t)
 '(whitespace-action nil)
 '(winner-mode t nil (winner))
 '(writeroom-disable-mode-line nil)
 '(writeroom-width 78)
 '(yas-global-mode t nil (yasnippet))
 '(yas-use-menu t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(mumamo-background-chunk-major ((t nil)) t)
 '(mumamo-background-chunk-submode1 ((t nil)) t)
 '(mumamo-background-chunk-submode2 ((t nil)) t)
 '(mumamo-background-chunk-submode3 ((t nil)) t)
 '(mumamo-background-chunk-submode4 ((t nil)) t))
