(load-file "~/.emacs.d/languages/coffee-script.el")
(load-file "~/.emacs.d/languages/cucumber.el")
(load-file "~/.emacs.d/languages/elisp.el")
(load-file "~/.emacs.d/languages/erlang.el")
(load-file "~/.emacs.d/languages/markdown.el")
(load-file "~/.emacs.d/languages/php.el")
(load-file "~/.emacs.d/languages/ruby.el")
(load-file "~/.emacs.d/languages/yaml.el")
