(defun customizations-for-go-mode ()
  (interactive)
  (flyspell-prog-mode)
  (flycheck-mode)
  (linum-mode t)
  (fci-mode)
  (auto-complete-mode)
  (whitespace-mode)
  (subword-mode)
  (setq tab-width 4)
  (define-key go-mode-map (kbd "RET") 'electric-newline-and-maybe-indent)
)

(add-hook 'go-mode-hook 'customizations-for-go-mode)
(add-hook 'before-save-hook #'gofmt-before-save)
