(setq auto-mode-alist (cons '("\\.md" . markdown-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.mkd" . markdown-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.mkdn" . markdown-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.mdown" . markdown-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.markdown" . markdown-mode) auto-mode-alist))

(defun customizations-for-markdown-mode ()
  (interactive)
  (setq whitespace-action nil)
  (fci-mode)
  (linum-mode t)
  (flyspell-mode)
  (auto-fill-mode)
  (define-key markdown-mode-map (kbd "C-c p") 'markdown-preview))

(add-hook 'markdown-mode-hook 'customizations-for-markdown-mode)
