(defun customizations-for-python-mode ()
  (interactive)
  (flyspell-prog-mode)
  (linum-mode t)
  (fci-mode)
  (auto-complete-mode)
  (subword-mode)
  (highlight-indentation-mode)
  (highlight-indentation-current-column-mode)
  (define-key python-mode-map (kbd "RET") 'newline-and-indent))

(add-hook 'python-mode-hook 'customizations-for-python-mode)
