(add-to-list 'auto-mode-alist '("\\.tmuxtheme\\'" . sh-mode))

(defun customizations-for-sh-mode ()
  (interactive)
  (flyspell-prog-mode)
  (linum-mode t)
  (fci-mode)
  (auto-complete-mode)
  (subword-mode)
  (setq sh-basic-offset 2)
  (setq sh-indentation 2)
  (setq highlight-indentation-offset 2)
  (highlight-indentation-mode)
 (define-key sh-mode-map (kbd "RET") 'reindent-then-newline-and-indent))

(add-hook 'sh-mode-hook 'customizations-for-sh-mode)
